# Generated by Django 5.1.4 on 2025-04-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="custom_fields",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="is_network",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="school",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="app.school",
            ),
        ),
    ]
