# Generated by Django 5.1.4 on 2025-04-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_school_custom_fields_school_is_network_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="is_network",
        ),
    ]
