# Generated by Django 5.1.4 on 2025-04-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_school_is_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="school",
        ),
        migrations.AddField(
            model_name="user",
            name="schools",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="app.school"
            ),
        ),
    ]
