# Generated by Django 5.1.4 on 2025-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_user_school_user_schools"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
    ]
