# Generated by Django 5.1.4 on 2025-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_user_custom_fields_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
