# Generated by Django 5.1.4 on 2025-04-23 16:25

from django.db import migrations, models

import app.enumeration.room_type


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_roomuser_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="announcement_type",
            field=models.CharField(
                choices=[
                    ("Information", "INFORMATION"),
                    ("Urgent", "URGENT"),
                    ("Important", "IMPORTANT"),
                ],
                default="INFORMATION",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Announcement", "ANNOUNCEMENT"), ("Message", "MESSAGE")],
                default=app.enumeration.room_type.RoomType["MESSAGE"].value,
                max_length=50,
            ),
        ),
    ]
