# Generated by Django 5.1.4 on 2025-04-27 07:17

import django.db.models.deletion
from django.db import migrations, models


import app.enumeration.room_type


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_room_type"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="announcement_type",
            field=models.CharField(
                choices=[
                    ("Information", "INFORMATION"),
                    ("Urgent", "URGENT"),
                    ("Important", "IMPORTANT"),
                ],
                default="INFORMATION",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Announcement", "ANNOUNCEMENT"), ("Message", "MESSAGE")],
                default=app.enumeration.room_type.RoomType["MESSAGE"],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("file_url", models.CharField(blank=True, max_length=255, null=True)),
                ("parent_id", models.CharField(max_length=50)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.CharField(blank=True, max_length=50, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
