# Generated by Django 5.1.4 on 2025-04-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_room_announcement_type_alter_room_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolDocument",
        ),
    ]
