# Generated by Django 5.1.4 on 2025-04-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_delete_schooldocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="agency_entity_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agency",
            name="agency_user_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agency",
            name="board_member_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agency",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agency",
            name="network_entity_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agency",
            name="school_entity_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agency",
            name="school_user_fields",
            field=models.JSONField(default=dict),
        ),
    ]
