# Generated by Django 5.1.4 on 2025-04-30 01:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_agency_agency_entity_fields_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="receiver",
            new_name="receiver_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="agency_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="agency_user_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="application_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="comment_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="complaint_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="links",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="report_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="school_ids",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="announcement_type",
            field=models.CharField(
                choices=[
                    ("Information", "INFORMATION"),
                    ("Urgent", "URGENT"),
                    ("Important", "IMPORTANT"),
                ],
                default="Information",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Announcement", "ANNOUNCEMENT"), ("Message", "MESSAGE")],
                default="Message",
                max_length=50,
            ),
        ),
    ]
