# Generated by Django 5.1.4 on 2025-04-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_receiver_notification_receiver_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="school_ids",
            field=models.JSONField(default=set, null=True),
        ),
    ]
