# Generated by Django 5.1.4 on 2025-04-30 12:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_user_reset_token_user_reset_token_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="board_meetings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(), blank=True, default=list, size=None
            ),
        ),
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("start_term", models.DateField(blank=True, null=True)),
                ("end_term", models.DateField(blank=True, null=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_members",
                        to="app.school",
                    ),
                ),
            ],
        ),
    ]
