# Generated by Django 5.1.4 on 2025-05-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_user_invitated_by_user_invitation_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_backup_codes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_temp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_temp_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
