# Generated by Django 5.1.4 on 2025-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_user_mfa_backup_codes_user_mfa_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mfa_method",
            field=models.JSONField(default=list),
        ),
    ]
