# Generated by Django 5.1.4 on 2025-05-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_user_mfa_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="agency_user_id",
            new_name="new_user_id",
        ),
    ]
