# Generated by Django 5.1.4 on 2025-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_rename_agency_user_id_notification_new_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="county",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="state",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="years_operation",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
