# Generated by Django 5.1.4 on 2025-05-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_agency_city_agency_county_agency_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcategory",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.agency",
            ),
        ),
    ]
