# Generated by Django 5.1.4 on 2025-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_reportcategory_agency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardmember",
            name="school",
        ),
        migrations.AddField(
            model_name="boardmember",
            name="schools",
            field=models.ManyToManyField(related_name="board_members", to="app.school"),
        ),
    ]
