# Generated by Django 5.1.4 on 2025-05-15 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_agency_zipcode_school_contact_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmember",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.agency",
            ),
        ),
    ]
