# Generated by Django 5.1.4 on 2025-05-16 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_boardmember_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transparencydetail",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
