# Generated by Django 5.1.4 on 2025-05-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_transparencydetail_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agency",
            old_name="agency_title",
            new_name="id",
        ),
    ]
