# Generated by Django 5.1.4 on 2025-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_rename_agency_title_agency_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="agency_unique_id",
        ),
        migrations.AddField(
            model_name="agency",
            name="title",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
