# Generated by Django 5.1.4 on 2025-05-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_remove_agency_agency_unique_id_agency_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="announcement_type",
        ),
        migrations.CreateModel(
            name="AnnouncementCategory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_categories",
                        to="app.agency",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="announcement_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="app.announcementcategory",
            ),
        ),
    ]
