# Generated by Django 5.1.4 on 2025-05-28 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_room_announcement_type_announcementcategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SchoolReport",
            new_name="SchoolSubmission",
        ),
        migrations.RemoveField(
            model_name="schoolsubmission",
            name="report",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="report",
        ),
        migrations.AddField(
            model_name="schoolsubmission",
            name="report_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.reportschedule",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="report_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.reportschedule",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="authorize_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("University", "University"),
                    ("County", "County"),
                    ("District", "District"),
                    ("State-Wide", "State-Wide"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="jurisdiction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("State", "State"),
                    ("Country", "Country"),
                    ("City", "City"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
