# Generated by Django 5.1.4 on 2025-05-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_rename_schoolreport_schoolsubmission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsubmission",
            name="report_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.reportschedule"
            ),
        ),
    ]
