# Generated by Django 5.1.4 on 2025-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_schoolsubmission_report_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="invitation_token_used",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
