# Generated by Django 5.1.4 on 2025-06-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_report_created_at_report_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="status",
        ),
    ]
