# Generated by Django 5.1.4 on 2025-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_remove_school_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
