# Generated by Django 5.1.4 on 2025-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_alter_document_name_alter_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="school_year",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
